#!/usr/bin/env bash
# displays "to infinity and beyond" indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal

trap "echo I am invincible!!!" SIGTERM
counter=1

while [ $counter ]
do
    echo "To infinity and beyond"
    sleep 2
    ((counter++))
done
