#!/usr/bin/env bash
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

counter=1

while [ $counter -le 10 ]
do
	if [ $((counter)) == 8 ]; then
	     echo "good luck"
	elif [ $((counter)) == 4 ]; then
	     echo "bad luck"
	else
	     echo "Best School"
	fi
    	((counter++))
done